git-repo/agvoy-app-03/src/Entity/UnavailablePeriod.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UnavailablePeriodRepository")
 */
class UnavailablePeriod
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $beginning;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $end_date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Room", inversedBy="unavailablePeriods")
     */
    private $relation;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBeginning(): ?\DateTimeInterface
    {
        return $this->beginning;
    }

    public function setBeginning(\DateTimeInterface $beginning): self
    {
        $this->beginning = $beginning;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(?\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getRelation(): ?Room
    {
        return $this->relation;
    }

    public function setRelation(?Room $relation): self
    {
        $this->relation = $relation;

        return $this;
    }
    
    public function __toString() {
        return (string) $this->getId();
    }
}

git-repo/agvoy-app-03/src/Form/UnavailablePeriodType.php
<?php

namespace App\Form;

use App\Entity\UnavailablePeriod;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UnavailablePeriodType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('beginning')
            ->add('end_date')
            ->add('relation')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => UnavailablePeriod::class,
        ]);
    }
}

git-repo/agvoy-app-03/src/Controller/UnavailablePeriodController.php
<?php

namespace App\Controller;

use App\Entity\UnavailablePeriod;
use App\Form\UnavailablePeriodType;
use App\Repository\UnavailablePeriodRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/unavailable/period")
 */
class UnavailablePeriodController extends AbstractController
{
    /**
     * @Route("/", name="unavailable_period_index", methods={"GET"})
     */
    public function index(UnavailablePeriodRepository $unavailablePeriodRepository): Response
    {
        return $this->render('unavailable_period/index.html.twig', [
            'unavailable_periods' => $unavailablePeriodRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="unavailable_period_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $unavailablePeriod = new UnavailablePeriod();
        $form = $this->createForm(UnavailablePeriodType::class, $unavailablePeriod);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($unavailablePeriod);
            $entityManager->flush();

            return $this->redirectToRoute('unavailable_period_index');
        }

        return $this->render('unavailable_period/new.html.twig', [
            'unavailable_period' => $unavailablePeriod,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="unavailable_period_show", methods={"GET"})
     */
    public function show(UnavailablePeriod $unavailablePeriod): Response
    {
        return $this->render('unavailable_period/show.html.twig', [
            'unavailable_period' => $unavailablePeriod,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="unavailable_period_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, UnavailablePeriod $unavailablePeriod): Response
    {
        $form = $this->createForm(UnavailablePeriodType::class, $unavailablePeriod);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('unavailable_period_index');
        }

        return $this->render('unavailable_period/edit.html.twig', [
            'unavailable_period' => $unavailablePeriod,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="unavailable_period_delete", methods={"DELETE"})
     */
    public function delete(Request $request, UnavailablePeriod $unavailablePeriod): Response
    {
        if ($this->isCsrfTokenValid('delete'.$unavailablePeriod->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($unavailablePeriod);
            $entityManager->flush();
        }

        return $this->redirectToRoute('unavailable_period_index');
    }
}

git-repo/agvoy-app-03/templates/unavailable_period/_delete_form.html.twig
<form method="post" action="{{ path('unavailable_period_delete', {'id': unavailable_period.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ unavailable_period.id) }}">
    <button class="btn">Delete</button>
</form>

git-repo/agvoy-app-03/templates/unavailable_period/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

git-repo/agvoy-app-03/templates/unavailable_period/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit UnavailablePeriod{% endblock %}

{% block body %}
    <h1>Edit UnavailablePeriod</h1>

    {{ include('unavailable_period/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('unavailable_period_index') }}">back to list</a>

    {{ include('unavailable_period/_delete_form.html.twig') }}
{% endblock %}

git-repo/agvoy-app-03/templates/unavailable_period/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}UnavailablePeriod index{% endblock %}

{% block body %}
    <h1>UnavailablePeriod index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Beginning</th>
                <th>End_date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for unavailable_period in unavailable_periods %}
            <tr>
                <td>{{ unavailable_period.id }}</td>
                <td>{{ unavailable_period.beginning ? unavailable_period.beginning|date('Y-m-d') : '' }}</td>
                <td>{{ unavailable_period.endDate ? unavailable_period.endDate|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('unavailable_period_show', {'id': unavailable_period.id}) }}">show</a>
                    <a href="{{ path('unavailable_period_edit', {'id': unavailable_period.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('unavailable_period_new') }}">Create new</a>
{% endblock %}

git-repo/agvoy-app-03/templates/unavailable_period/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New UnavailablePeriod{% endblock %}

{% block body %}
    <h1>Create new UnavailablePeriod</h1>

    {{ include('unavailable_period/_form.html.twig') }}

    <a href="{{ path('unavailable_period_index') }}">back to list</a>
{% endblock %}

git-repo/agvoy-app-03/templates/unavailable_period/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}UnavailablePeriod{% endblock %}

{% block body %}
    <h1>UnavailablePeriod</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ unavailable_period.id }}</td>
            </tr>
            <tr>
                <th>Beginning</th>
                <td>{{ unavailable_period.beginning ? unavailable_period.beginning|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>End_date</th>
                <td>{{ unavailable_period.endDate ? unavailable_period.endDate|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('unavailable_period_index') }}">back to list</a>

    <a href="{{ path('unavailable_period_edit', {'id': unavailable_period.id}) }}">edit</a>

    {{ include('unavailable_period/_delete_form.html.twig') }}
{% endblock %}